export const SET_USER = "SET_USER";
export const SET_PARTNER = "SET_PARTNER";
export const UPDATE_LIKED_NAMES = "UPDATE_LIKED_NAMES";
export const UPDATE_SEEN_NAMES = "UPDATE_SEEN_NAMES";
export const GET_LIKED_NAMES = "GET_LIKED_NAMES";
export const GET_SEEN_NAMES = "GET_SEEN_NAMES";
export const GET_PARTNER_NAMES = "GET_PARTNER_NAMES";
export const UPDATE_PARTNER_NAMES = "UPDATE_PARTNER_NAMES";
export const FIND_MATCHES = "FIND_MATCHES";
export const LINK_ACCOUNT = "LINK_ACCOUNT";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const SET_LOADING = "SET_LOADING";


