name: Node Continuous Integration

on:
  pull_request:
    branches: [main]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12"

      - name: Install Dependencies
        working-directory: server
        run: npm ci

      - name: Connect to PostgreSQL database
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432

      - name: Testing
        run: npm test
