name: Node Continuous Integration

on:
  pull_request:
    branches: [main]   

jobs:
    test_pull_request:
        steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v2
            with:
              node-version: '12'
              check-latest: true
          - name: NPM CI
            working-directory: ./server
            run: npm ci
            run: npm test
         